cmake_minimum_required(VERSION 3.10)

set(OLD_BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR})
set(CMAKE_CURRENT_BINARY_DIR ${CMAKE_BINARY_DIR}/proto)
protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS ${PROTOBUF_FILES})
set(CMAKE_CURRENT_BINARY_DIR  ${OLD_BINARY_DIR})
unset(OLD_BINARY_DIR)